default:
	javac -cp org.json-20120521.jar *.java
runTS:
	java -cp .:org.json-20120521.jar ThghtShreGen
runStats:
	java -cp .:org.json-20120521.jar thghtShreStats
runStatsOutput:
       java -cp .:org.json-20120521.jar thghtShreStats outputStats.json