default:
	javac -cp org.json-20120521.jar *.java
runExp1:
	java -cp .:org.json-20120521.jar Experiment
runBF:
	java -cp .:org.json-20120521.jar BeFuddledGen
runBFstats:
	java -cp .:org.json-20120521.jar beFuddledStats
runBFstatsOutput:
	java -cp .:org.json-20120521.jar beFuddledStats outputStats.txt
runTS:
	java -cp .:org.json-20120521.jar ThghtShreGen
runTSstats:
	java -cp .:org.json-20120521.jar thghtShreStats
runTSstatsOutput:
       java -cp .:org.json-20120521.jar thghtShreStats outputStats.json
