default:
	javac -cp org.json-20120521.jar *.java
runBF:
	java -cp .:org.json-20120521.jar BeFuddledGen
runBFstats:
	java -cp .:org.json-20120521.jar beFuddledStats
runBFstatsOutput:
	java -cp .:org.json-20120521.jar beFuddledStats outputStats.txt
runTS:
	java -cp .:org.json-20120521.jar ThghtShreGen
runTSstats:
	java -cp .:org.json-20120521.jar thghtShreStats
runTSstatsOutput:
       java -cp .:org.json-20120521.jar thghtShreStats outputStats.json
runExpMem:
	java -cp .:org.json-20120521.jar ExperimentBFmem
runExpTime:
	java -cp .:org.json-20120521.jar ExperimentTime
runExpShardBF:
	java -cp .:org.json-20120521.jar ExperimentShardBF
runExpShardRand:
	java -cp .:org.json-20120521.jar ExperimentShardRand
